name: Deploy static site to GitHub Pages (using official actions)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - list repo root
        run: |
          echo "Working directory: $(pwd)"
          ls -la

      - name: Debug - list three-page-website folder
        run: |
          ls -la three-page-website || true

      - name: Debug - list publish folder
        run: |
          echo "Listing three-page-website/public:" 
          ls -la three-page-website/public || true

      - name: Archive site
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./three-page-website/public

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

